### ISSUE TITLE
Quote Generation

### ISSUE THREAD

**Issue by ghost** [intel/crypto-api-toolkit#1]
Hello, 

I'm curious to know the reasoning behind these two restrictions: 

1. The key used to generate a quote cannot be created with CKA_TOKEN attribute set to true. It must be a session key object.
2. The key used to generate a quote cannot be used for sign and verify operations in addition to encryption and decryption operations.

What if I want to generate a quote on a key that will be used later to sign messages, that key needs to persist (i.e. token not session) and used for sign operations? I'm thinking of changing the code to bypass these restrictions, but is there a better way to solve my issue?

Thanks

**Comment by svenkata9** [comment]
Hi @hgalal88,

Both these restrictions come from a security aspect. The first one is to avoid generating the same quote (the same public key shouldn't be used for generating the quote). If it persists (in the token), it will introduce this possibility. The second restriction is mostly from how and for what a quote is used for - typically for attesting the platform and provisioning secrets. For that reason, it is limited to only unwrap, thus preventing other crypto operations.
