### ISSUE TITLE
Support signing the enclave with an external key

### ISSUE THREAD

**Issue by ipuustin** [intel/crypto-api-toolkit#4]
Currently when using `make` the enclave is automatically signed using the "test signing key" which is present in the repository. It would be better if there was at least a ./configure switch to disable automatic signing. Even better, the default might be to not sign the enclave at all when running make, but instead have a signing key argument to ./configure script if signing was needed. This would have the following benefits:
1) easily let external signing systems use the unsigned enclave
2) let users easily bring in the external signing key to the build process
3) prevent mistakes where people accidentally use the test signing key to sign production enclaves

Then, in order to preserve the current behavior, the users would need to do this before running `make`:

    ./configure --enclave-signing-key=src/p11/enclave_config/p11Enclave_private.pem

Even better, the "test signing key" could be removed from the repository and an extra step could be added to the documentation where the user would generate a private key to be used for signing:

    openssl genrsa -3 -out key.pem 3072
    ./configure --enclave-signing-key=key.pem

**Comment by svenkata9** [comment]
Ismo, The signing process is documented in SGX SDK. For building crypto-api-toolkit with a custom key, all you need to do is to replace the [privateKey.pem ](https://github.com/intel/crypto-api-toolkit/blob/master/src/p11/enclave_config/p11Enclave_private.pem) in src/p11/enclave_config directory which can be done just via a shell script command before you run configure.
